---
title: "R Notebook Data Exploration"
output: html_notebook
---
Read data and transform data frame
```{r}
data <- read.csv("dontpatronizeme_v1.4/dontpatronizeme_categories.tsv", sep = '\t', header = F)
#drop irrelevant columns and empty rows
data <-  data[-c(1:3),-c(1:3, 6:8)]
#rename columns
names(data) <- c("vul_cat", "country", "pcl_cat", "annotator") 

```

Basic overview
```{r}
countries <- xtabs(~data$country, data = data)
pcl <- xtabs(~data$pcl_cat, data = data)
vul <- xtabs(~data$vul_cat, data = data)

library(RColorBrewer)
palette <- brewer.pal(8, "Set2") 
palette2 <- brewer.pal(8, "Pastel2") 

barplot(sort(countries), 
        las = 2, 
        col=palette, 
        main = "Countries in data")
names = c("The p., the m.", "Shallow solution", "Metaphors", "Authority voice", "Presupp.", "Compassion", "Unb. power rel.")
par(mar=c(7.5,4,4,2)) 
plot <- barplot(sort(pcl),
                names.arg = names,
                las = 2,
                col=palette,
                main ="PCL categories in data", 
                ylim = c(0,1100))

text(x = plot, y = sort(pcl) + 40, labels = sort(pcl))

barplot(sort(vul),
        col=palette,
        las = 2, 
        main = "Vulnerable groups in data")

```

Plots of frequencies in data
```{r}
mosaicplot(data$country ~ data$vul_cat, 
           data=data,
           col= palette, 
           las = 1,
           main = "Countries and vulnerable groups", 
           ylab = "Group",
           xlab = "Countries")
mosaicplot(data$vul_cat ~ data$pcl_cat, 
           data=data,
           col= palette, 
           las = 2,
           main = "Vulnerable groups and PCL categories", 
           ylab = "Category",
           xlab = "Group")
mosaicplot(data$pcl_cat ~ data$vul_cat, 
           data=data,
           col= palette, 
           las = 2,
           main = "PCL categories and vulnerable groups", 
           ylab = "Group",
           xlab = "Category")
mosaicplot(data$country ~ data$pcl_cat, 
           data=data,
           col= palette, 
           las = 1,
           main = "PCL categories and countries", 
           ylab = "Categories",
           xlab = "Countries")

```
Plots of smaller data set with only unambiguous cases of PCL
```{r}
data_unambig <- data[data$annotator == 2,]

mosaicplot(data_unambig$country ~ data_unambig$vul_cat, 
           data=data_unambig,
           col= palette2, 
           las = 1,
           main = "Vulnerable groups and countries, unambiguous data", 
           ylab = "Group",
           xlab = "Country"
           )
mosaicplot(data_unambig$vul_cat ~ data_unambig$pcl_cat, 
           data=data_unambig,
           col= palette2, 
           las = 2,
           main = "PCL categories and vulnerable groups, unambiguous data", 
           ylab = "Category",
           xlab = "Group")
mosaicplot(data_unambig$country ~ data_unambig$pcl_cat, 
           data=data_unambig,
           col= palette2,
           las = 1,
           main = "PCL categories and countries, unambiguous data", 
           ylab = "Category",
           xlab = "Country")
```
## Some exploration of the results of the lower level label BiLSTMs

```{r}
pcl
# How often did a category appear in the data? (not taking into account that we later deleted one paragraph)
num_cat <- c(968, 285, 227, 296, 682, 250, 52)
# F1 scores of the simple model
scores_cat <- c(87.36, 45.57, 43.24, 36.36, 65.43, 31.75, 0)
# F1 scores of the 10-fold cross validation model
scores_cat2 <- c(86.71, 46.15, 42.86, 28.99, 59.09, 31.25, 0)


#correlation coefficient simple BiLSTM
cor(num_cat, scores_cat, method = "pearson" )
#correlation coefficient BiLSTM kCV
cor(num_cat, scores_cat2, method = "pearson" )


plot(num_cat, scores_cat, ylab = "F1", xlab = "Number of category instance in the data", main = "Simple BiLSTM")
plot(num_cat, scores_cat2, ylab = "F1", xlab = "Number of category instance in the data", main = "10-fold cross validation BiLSTM")

```
